import {download} from './site.js';import{empty,source,importClaims,restore,csv,prompt}from './core.js';import{standalone}from './standalone.js';
const $=s=>document.querySelector(s);let state=empty();try{const raw=localStorage.getItem('observatorio-v1');if(raw){const saved=JSON.parse(raw);state=restore(saved);state.claims.forEach((c,i)=>{const old=saved.claims[i];if(['Respaldada','Parcial','No respaldada'].includes(old.status)&&old.reviewer&&old.note)Object.assign(c,{status:old.status,reviewer:old.reviewer,note:old.note,reviewedAt:old.reviewedAt||''})})}}catch{msg('No se pudo recuperar el guardado local. Puedes importar un respaldo.')}
function msg(t){$('#message').textContent=t}function save(){try{localStorage.setItem('observatorio-v1',JSON.stringify(state));return true}catch{msg('No se pudo guardar localmente. Exporta un respaldo antes de cerrar.');return false}}
function run(fn){try{fn()}catch(e){msg(e.message)}}function fields(){ $('#project').value=state.config.title;$('#question').value=state.config.question;$('#criteria').value=state.config.criteria}
function render(){fields();$('#sources').replaceChildren();$('#csource').replaceChildren();state.sources.forEach(s=>{const li=document.createElement('li');li.textContent=`${s.id} · ${s.title} · DOI: ${s.doi||'No registrado'} · WoS: ${s.wos}`;$('#sources').append(li);const o=document.createElement('option');o.value=s.id;o.textContent=s.id+' · '+s.title;$('#csource').append(o)});$('#counts').textContent=`${state.sources.length} fuentes · ${state.claims.length} afirmaciones · ${state.claims.filter(c=>c.status!=='Pendiente').length} revisadas`;$('#claims').replaceChildren();state.claims.forEach((c,i)=>{if($('#filter').value!=='Todos'&&$('#filter').value!==c.status)return;const box=document.createElement('article');box.className='card';const title=document.createElement('h3');title.textContent=c.claim;const meta=document.createElement('p');meta.textContent=`${c.sourceId} · página ${c.page} · ${c.status}`;const quote=document.createElement('blockquote');quote.textContent=c.quote;const form=document.createElement('form');form.innerHTML=`<label for="status-${i}">Decisión humana</label><select id="status-${i}"><option>Pendiente</option><option>Respaldada</option><option>Parcial</option><option>No respaldada</option></select><label for="reviewer-${i}">Revisor/a (nombre o código)</label><input id="reviewer-${i}" required><label for="note-${i}">Justificación y localización comprobada</label><textarea id="note-${i}" required></textarea><button>Guardar revisión</button>`;form.querySelector('select').value=c.status;form.querySelector('input').value=c.reviewer;form.querySelector('textarea').value=c.note;form.onsubmit=e=>{e.preventDefault();c.status=form.querySelector('select').value;c.reviewer=form.querySelector('input').value.trim();c.note=form.querySelector('textarea').value.trim();if(!c.reviewer||!c.note)return msg('Incluye revisor y justificación.');c.reviewedAt=new Date().toISOString();save();render();msg('Revisión registrada. La decisión corresponde a la persona revisora.')};box.append(title,meta,quote,form);$('#claims').append(box)})}
$('#config').onsubmit=e=>{e.preventDefault();state.config={title:$('#project').value.trim(),question:$('#question').value.trim(),criteria:$('#criteria').value.trim()};if(save())msg('Configuración guardada.')};
$('#source').onsubmit=e=>{e.preventDefault();run(()=>{const s=source({id:$('#sid').value,title:$('#stitle').value,doi:$('#doi').value,wos:$('#wos').value});if(state.sources.some(x=>x.id===s.id))throw Error('Este identificador ya existe. Usa otro.');state.sources.push(s);save();render();$('#source').reset();$('#wos').value='Pendiente de comprobación institucional';msg('Fuente registrada. El dato WoS es una anotación humana, no una comprobación automática.')})};
$('#generate').onclick=()=>{if(!state.sources.length)return msg('Registra al menos una fuente.');$('#prompt').textContent=prompt(state);msg('Copia la instrucción en Acrobat con los mismos documentos cargados.')};
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#prompt').textContent);msg('Instrucción copiada.')}catch{msg('Selecciona y copia el texto de la instrucción.')}};
$('#import').onclick=()=>run(()=>{const values=JSON.parse($('#json').value);const claims=importClaims(values,state.sources);state.claims.push(...claims);save();render();msg(claims.length+' afirmaciones importadas como pendientes.')});
$('#claim').onsubmit=e=>{e.preventDefault();run(()=>{state.claims.push(...importClaims([{sourceId:$('#csource').value,claim:$('#ctext').value,page:$('#cpage').value,quote:$('#cquote').value}],state.sources));save();render();$('#claim').reset();msg('Afirmación añadida para revisión.')})};
$('#filter').onchange=render;$('#backup').onclick=()=>download('observatorio-respaldo.json',JSON.stringify(state,null,2));$('#export').onclick=()=>download('matriz-evidencia.csv',csv([['fuente','titulo','doi','wos','afirmacion','pagina','pasaje','estado','revisor','nota','fecha'],...state.claims.map(c=>{const s=state.sources.find(s=>s.id===c.sourceId);return[c.sourceId,s.title,s.doi,s.wos,c.claim,c.page,c.quote,c.status,c.reviewer,c.note,c.reviewedAt]})]),'text/csv;charset=utf-8');
$('#restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>5e6)return msg('Archivo demasiado grande: máximo 5 MB.');try{const next=restore(JSON.parse(await f.text()));if(!confirm('¿Sustituir el proyecto actual? Exporta primero si deseas conservarlo. Las revisiones importadas quedarán pendientes.'))return;state=next;save();render();msg('Respaldo recuperado. Se requiere revisar nuevamente las afirmaciones.')}catch(err){msg(err.message)}e.target.value=''};
$('#demo').onclick=()=>{const id='DEMO-'+(state.sources.length+1);state.sources.push({id,title:'Caso ficticio para practicar: lectura en un laboratorio',doi:'',wos:'No aplica: material sintético, no es un artículo'});state.claims.push(...importClaims([{sourceId:id,claim:'En este ejercicio participaron 12 personas.',page:'1',quote:'En el escenario ficticio participaron 12 personas que revisaron tres documentos.'},{sourceId:id,claim:'La IA mejora todos los proyectos de investigación.',page:'1',quote:'En el escenario ficticio participaron 12 personas que revisaron tres documentos.'}],state.sources));save();render();msg('Demostración sintética añadida. La segunda afirmación excede el pasaje: úsala para practicar la revisión.')};
$('#standalone').onclick=()=>download('mi-observatorio.html',standalone(state.config),'text/html;charset=utf-8');render();
