// Casos originales y ficticios. No son resúmenes de publicaciones ni resultados de modelos.
export const challenges=[
{id:'C1',title:'El efecto que apareció después del ajuste',evidence:'Caso sintético. Un estudio observacional comparó 820 personas que eligieron participar en un programa y 760 que no participaron. La asociación ajustada fue positiva. La motivación previa no se midió y los autores reconocen que puede explicar parte de la selección. No se aplicó una estrategia de identificación causal adicional.',claim:'El programa causó una mejora, porque el ajuste multivariable descartó el sesgo de selección.',gold:0,explanation:'El ajuste por variables observadas no descarta selección por motivación no medida. La afirmación agrega identificación causal que el diseño descrito no proporciona.'},
{id:'C2',title:'Una diferencia no significativa',evidence:'Caso sintético. La diferencia estimada entre dos procedimientos fue 0,09 unidades; intervalo de confianza del 95%: −0,12 a 0,30. El contraste de diferencia produjo p = 0,31. No se definió margen de equivalencia ni se diseñó una prueba de equivalencia.',claim:'Los procedimientos son equivalentes, ya que no se encontró una diferencia estadísticamente significativa.',gold:0,explanation:'El resultado no significativo no demuestra equivalencia. El intervalo admite diferencias de distinto signo y no hay margen de equivalencia definido.'},
{id:'C3',title:'Dos artículos, una sola cohorte',evidence:'Caso sintético. Dos publicaciones analizan distintos desenlaces de las mismas 1.120 personas, reclutadas en los mismos centros y fechas. La segunda declara reutilizar la cohorte de la primera. Ambas reportan asociaciones favorables.',claim:'Las publicaciones amplían los desenlaces examinados, pero no constituyen dos replicaciones independientes con nuevas muestras.',gold:1,explanation:'La afirmación preserva la dependencia de la muestra y no niega que las publicaciones puedan aportar desenlaces distintos.'},
{id:'C4',title:'Un modelo preciso dentro de casa',evidence:'Caso sintético. Un clasificador alcanzó AUROC 0,91 mediante validación interna estratificada en una institución. No se evaluó calibración externa ni cambio de prevalencia. El manuscrito propone una validación futura en otros contextos.',claim:'El AUROC interno permite recomendar el despliegue del clasificador en instituciones con prevalencias diferentes.',gold:0,explanation:'Discriminación interna no demuestra transportabilidad ni calibración en el entorno de destino. La recomendación omite la validación pendiente.'},
{id:'C5',title:'Una interpretación rival',evidence:'Caso sintético. Un estudio histórico de correspondencia institucional identifica dos lecturas compatibles con las cartas conservadas. El archivo excluye comunicaciones orales y parte de las cartas privadas. No existe una fuente que permita resolver la intención individual de los actores.',claim:'Con este corpus no es posible adjudicar de manera concluyente una intención individual; debe conservarse la interpretación rival.',gold:1,explanation:'La afirmación reconoce los límites del archivo y no convierte una lectura posible en una intención demostrada.'},
{id:'C6',title:'La novedad de un corpus pequeño',evidence:'Caso sintético. Una búsqueda por dos expresiones exactas recuperó ocho artículos en una colección. Ninguno utilizó una combinación metodológica concreta. No se buscaron sinónimos ni equivalentes conceptuales; tampoco se revisaron referencias citadas.',claim:'La combinación metodológica constituye una contribución inédita en la literatura internacional.',gold:0,explanation:'La ausencia en esa búsqueda acotada no demuestra novedad global. Hacen falta una búsqueda de antecedentes conceptuales y una formulación proporcional a su alcance.'}
];
export const demoCases=[
{id:'D1',split:'desarrollo',question:'¿El ajuste observacional elimina la confusión no medida?',expected:'No respaldada',critical:true,a:'Respaldada',b:'No respaldada',note:'Caso sintético de identificación causal.'},
{id:'D2',split:'desarrollo',question:'¿La muestra fue de 1120 participantes según el pasaje?',expected:'Respaldada',critical:false,a:'Respaldada',b:'Respaldada',note:'Dato explícito del caso ficticio.'},
{id:'D3',split:'desarrollo',question:'¿Se informó el mecanismo molecular?',expected:'Abstención',critical:false,a:'Respaldada',b:'Abstención',note:'No está en el corpus ficticio.'},
{id:'D4',split:'desarrollo',question:'¿Dos artículos de una cohorte son replicaciones independientes?',expected:'No respaldada',critical:true,a:'No respaldada',b:'No respaldada',note:'Control de dependencia.'},
{id:'R1',split:'reserva',question:'¿p > 0,05 demuestra equivalencia?',expected:'No respaldada',critical:true,a:'Respaldada',b:'Abstención',note:'Caso sintético; sin margen de equivalencia.'},
{id:'R2',split:'reserva',question:'¿El documento indica validación externa pendiente?',expected:'Respaldada',critical:false,a:'Respaldada',b:'Respaldada',note:'Dato explícito del caso ficticio.'},
{id:'R3',split:'reserva',question:'¿Conocemos la intención individual en el archivo incompleto?',expected:'Abstención',critical:false,a:'No respaldada',b:'Abstención',note:'Ausencia de evidencia decisiva.'},
{id:'R4',split:'reserva',question:'¿La búsqueda acotada demuestra novedad internacional?',expected:'No respaldada',critical:true,a:'Respaldada',b:'No respaldada',note:'No equivale a búsqueda exhaustiva.'}
];
