import './site.js';
import {download} from './site.js';
import {challenges,demoCases} from './challenge-data.js';
import {labels,validateCases,metrics,gate,brier} from './bench-core.js';
import {portableBench} from './portable-bench.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],history=[],contract=null,judgments=null;
try{const v=JSON.parse(localStorage.getItem('research-bench-v1')||'{}');if(v.rows?.length)rows=validateCases(v.rows);history=v.history||[];contract=v.contract||null;judgments=v.judgments||null;}catch{}
function save(){try{localStorage.setItem('research-bench-v1',JSON.stringify({rows,history,contract,judgments}));$('#bench-message').textContent='Registro guardado en este navegador.'}catch{$('#bench-message').textContent='No se pudo guardar. Descargue el informe antes de salir.'}}
$('#challenge-cards').innerHTML=challenges.map((c,i)=>`<fieldset class="panel"><legend>${i+1}. ${esc(c.title)}</legend><p>${esc(c.evidence)}</p><blockquote>${esc(c.claim)}</blockquote><label>Probabilidad de respaldo (%)<input name="p${i}" type="number" min="0" max="100" required></label><label>Justificación o posible objeción<textarea name="j${i}" minlength="20" required></textarea></label></fieldset>`).join('');
$('#challenge-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),p=challenges.map((_,i)=>Number(f.get('p'+i)));judgments=challenges.map((c,i)=>({id:c.id,probability:p[i],justification:f.get('j'+i),gold:c.gold}));save();$('#challenge-results').innerHTML=`<h3>Puntuación de Brier: ${brier(p,challenges.map(c=>c.gold)).toFixed(3)}</h3><p>Promedio de (probabilidad − referencia)², con probabilidades entre 0 y 1. Un valor menor indica menor error en estos seis casos. Este ejercicio no estima su competencia ni permite diagnosticar calibración con una muestra tan pequeña.</p>${challenges.map(c=>`<details open><summary>${esc(c.title)} · ${c.gold?'Respaldada':'No respaldada'}</summary><p>${esc(c.explanation)}</p></details>`).join('')}`;};
function contractStatus(){ $('#protocol-status').textContent=contract?`Contrato v${history.length}, registrado ${contract.date}. Los cálculos usan esta versión guardada. Los cambios del formulario requieren fijar una nueva versión.`:'Todavía no se ha fijado un contrato.'; }
if(contract)for(const [k,v]of Object.entries(contract)){const el=$('#protocol').elements.namedItem(k);if(el)el.value=v;}contractStatus();
$('#protocol').onsubmit=e=>{e.preventDefault();contract=Object.fromEntries(new FormData(e.target));contract.date=new Date().toISOString();history.push({...contract});contractStatus();save();$('#metrics').textContent='Contrato actualizado. Vuelva a calcular los resultados.'};
function render(){ $('#case-editor').innerHTML=rows.map((r,i)=>`<details><summary>${esc(r.id)} · ${esc(r.split)} · ${esc(r.question)}</summary><p>Referencia adjudicada: <strong>${esc(r.expected)}</strong>. Error crítico: ${r.critical?'sí':'no'}.</p>${['a','b'].map(k=>`<label>Respuesta clasificada de ${k.toUpperCase()}<select data-row="${i}" data-condition="${k}"><option value="">Sin ejecutar</option>${labels.map(l=>`<option ${r[k]===l?'selected':''}>${l}</option>`).join('')}</select></label>`).join('')}<label>Pasaje, respuesta original y nota de adjudicación<textarea data-note="${i}">${esc(r.note)}</textarea></label></details>`).join('');document.querySelectorAll('[data-row]').forEach(el=>el.onchange=()=>{rows[el.dataset.row][el.dataset.condition]=el.value;save();$('#metrics').textContent='Datos modificados. Vuelva a calcular.'});document.querySelectorAll('[data-note]').forEach(el=>el.oninput=()=>{rows[el.dataset.note].note=el.value;save()});}
$('#load-demo').onclick=()=>{if(rows.length&&!confirm('¿Sustituir el banco actual por datos ficticios? Descargue antes su informe si quiere conservarlo.'))return;rows=validateCases(demoCases);render();save();$('#metrics').textContent='Demostración ficticia cargada. No son resultados de una ejecución real.'};
$('#template').onclick=()=>download('plantilla-casos.json',JSON.stringify(demoCases.map(r=>({...r,a:'',b:'',note:'Sustituya por su evidencia y adjudicación; caso ficticio de plantilla.'})),null,2));
$('#cases-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>5000000)throw Error('Archivo superior a 5 MB.');const next=validateCases(JSON.parse(await f.text()));if(rows.length&&!confirm('¿Sustituir el banco actual por el archivo validado?'))return;rows=next;render();save();$('#metrics').textContent='Banco importado. Vuelva a calcular.'}catch(err){$('#bench-message').textContent=err.message}finally{e.target.value=''}};
const pct=n=>n===null?'No estimable':(100*n).toFixed(1)+'%';
function results(){return ['desarrollo','reserva'].flatMap(split=>['a','b'].map(condition=>({split,condition,...metrics(rows.filter(r=>r.split===split),condition)})))}
$('#evaluate').onclick=()=>{if(!contract||!rows.length){$('#metrics').textContent='Fije un contrato y cargue los casos antes de evaluar.';return;}$('#metrics').innerHTML=`<h3>Resultados descriptivos</h3><div class="table-wrap"><table><tr><th>Partición / condición</th><th>Evaluados</th><th>Exactitud</th><th>Cobertura</th><th>Riesgo selectivo</th><th>Críticos</th></tr>${results().map(m=>`<tr><td>${m.split} / ${m.condition.toUpperCase()}</td><td>${m.n}/${m.total}; faltan ${m.missing}</td><td>${m.correct}/${m.n} · ${pct(m.accuracy)}</td><td>${m.answered}/${m.n} · ${pct(m.coverage)}</td><td>${m.wrong}/${m.answered} · ${pct(m.risk)}</td><td>${m.critical}</td></tr>`).join('')}</table></div>${results().filter(m=>m.split==='reserva').map(m=>`<p><strong>Reserva ${m.condition.toUpperCase()}:</strong> ${gate(m,contract)}.</p>`).join('')}<p>Estos resultados describen el banco seleccionado. No demuestran superioridad poblacional ni autorizan un despliegue. Si se modificó el procedimiento tras consultar la reserva, esa partición debe considerarse desarrollo.</p>`};
$('#report').onclick=()=>download('informe-evaluacion.json',JSON.stringify({date:new Date().toISOString(),contract,history,cases:rows,results:results(),judgments,limitations:'Evaluación local descriptiva. Reserva visible. Sin validación externa; los casos de demostración son ficticios.'},null,2));
$('#portable').onclick=()=>{if(!contract||!rows.length){$('#bench-message').textContent='Fije el contrato y cargue los casos para construir la aplicación.';return;}download('banco-investigacion.html',portableBench(contract,rows),'text/html;charset=utf-8')};render();

if(Array.isArray(judgments))judgments.forEach((j,i)=>{if(i<challenges.length){document.querySelector(`[name="p${i}"]`).value=j.probability;document.querySelector(`[name="j${i}"]`).value=j.justification;}});
