import {labels,metrics,gate} from './bench-core.js';
export function portableBench(contract,rows){const json=v=>JSON.stringify(v).replaceAll('<','\\u003c');return `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Banco de evaluación de investigación</title><style>body{font:17px/1.6 Arial;margin:40px auto;max-width:1000px;padding:20px;color:#222}textarea,select{display:block;padding:10px;margin:10px 0}section{border-top:1px solid #aaa;padding:20px 0}button{padding:12px}pre{white-space:pre-wrap}</style><h1>Banco de evaluación de investigación</h1><p>Aplicación local sin conexión a un modelo. Las respuestas se ejecutan y adjudican fuera de esta página. El archivo contiene los casos exportados: revise su contenido antes de compartirlo.</p><p>Para modificar una regla abra este archivo en un editor y busque CONFIG o la función gate. Conserve una copia y pruebe casos en el umbral, sin respuestas y con un error crítico.</p><p id="question"></p><div id="cases"></div><button id="run">Evaluar reserva</button><button id="export">Exportar registro</button><pre id="result"></pre><script>
const CONFIG=${json(contract)};
const rows=${json(rows)};
const labels=${json(labels)};
${metrics.toString()}
${gate.toString()}
document.querySelector('#question').textContent=CONFIG.question;
rows.forEach((r,i)=>{const s=document.createElement('section');const p=document.createElement('p');p.textContent=r.id+' / '+r.split+': '+r.question+' — Referencia: '+r.expected;s.append(p);['a','b'].forEach(k=>{const l=document.createElement('label');l.textContent='Condición '+k.toUpperCase();const el=document.createElement('select');['',...labels].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v||'Sin ejecutar';o.selected=r[k]===v;el.append(o)});el.onchange=()=>r[k]=el.value;l.append(el);s.append(l)});document.querySelector('#cases').append(s)});
document.querySelector('#run').onclick=()=>{document.querySelector('#result').textContent=['a','b'].map(k=>{const m=metrics(rows.filter(r=>r.split==='reserva'),k);return k.toUpperCase()+': '+gate(m,CONFIG)+'\\n'+JSON.stringify(m,null,2)}).join('\\n\\n')+'\\nResultados descriptivos. Sin validación independiente.'};
document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({CONFIG,rows,date:new Date().toISOString()},null,2)],{type:'application/json'}));a.download='registro-banco.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
<\/script></html>`}
