export function standalone(config){const data=JSON.stringify(config).replaceAll('<','\\u003c');return `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mi observatorio</title><style>body{font:17px/1.6 Arial;max-width:850px;margin:40px auto;padding:20px;color:#202b35}label{display:block;margin-top:15px}input,textarea{width:100%;box-sizing:border-box;padding:10px;font:inherit}button{padding:12px;margin:12px 8px 12px 0}pre{white-space:pre-wrap;background:#f0f3f5;padding:20px}article{border:1px solid #bbb;padding:15px;margin:15px 0}</style><h1 id="title"></h1><p>Prototipo editable del taller 2. La generación ocurre en una IA externa; registra aquí la evidencia manualmente. Exporta antes de cerrar: esta versión no guarda automáticamente.</p><label>Pregunta<input id="question"></label><label>Criterio<input id="criterion"></label><button id="generate">Crear instrucción para la IA</button><pre id="prompt"></pre><form id="entry"><label>Fuente / DOI<input id="source" required></label><label>Afirmación<textarea id="claim" required></textarea></label><label>Página<input id="page" required></label><label>Pasaje<textarea id="quote" required></textarea></label><button>Añadir evidencia pendiente</button></form><div id="rows"></div><button id="export">Descargar resultados JSON</button><script>
// EJERCICIO: modifica CONFIG y REGLA. No incluyas claves ni datos privados.
const CONFIG = ${data};
const REGLA = 'Usa solo las fuentes cargadas. Incluye página y pasaje breve. Si falta evidencia escribe No reportado.';
const rows=[];const q=s=>document.getElementById(s);
q('title').textContent=CONFIG.title;q('question').value=CONFIG.question;q('criterion').value=CONFIG.criteria;
q('generate').onclick=()=>q('prompt').textContent=REGLA+' Pregunta: '+q('question').value+' Criterios: '+q('criterion').value;
q('entry').onsubmit=e=>{e.preventDefault();const item={source:q('source').value,claim:q('claim').value,page:q('page').value,quote:q('quote').value,status:'Pendiente'};rows.push(item);const card=document.createElement('article');card.textContent=JSON.stringify(item,null,2);q('rows').append(card);q('entry').reset()};
q('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({config:CONFIG,evidence:rows},null,2)],{type:'application/json'}));a.download='resultados-prototipo.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
<\/script></html>`}
